### ISSUE TITLE
Native eo3 document support

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-explorer#133]
eo3 documents already work in Explorer thanks to ODC 1.8's automatic conversion (which appends the legacy fields to the document on index), but they don't display very well in Explorer.

This we can improve:

- [x]  the geometry shown in explorer is the square bounding box. We could use the actual footprint available in eo3's native geometry. #162

- [x] support the `region_code` field for displaying grid counts #162
- [x] support for eo3 fields in the document renderer #167
- [x] expand stac api to make use of extra eo3 properties. grids, etc.

**Comment by jeremyh** [comment]
Closing. All mentioned items are done in the current release (2.2.3).
